import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>gta home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="its my mobit clone" />
        <link rel="icon" href="/gta-home-logo.jpg" />
      </Head>
      <div>salam</div>
      </>
  )
}

export default Home